# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(default='Pool de Ambulancia', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('dato_fecha', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.IntegerField()),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Person')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Fecha')),
            ],
        ),
    ]
