# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='dependencia',
            new_name='nombre_dependencia',
        ),
    ]
