# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_auto_20170805_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='nombre_dependencia',
            new_name='nombreDependencia',
        ),
    ]
